- hosts: webservers
  become: yes
  # gather_facts: no

  vars:
    conf_dir: /etc/nginx
    nginx_port: 80

  tasks:    
    - name: Copy postgres config file to folder
      ansible.builtin.template:
        src: templates/postgresql.conf.j2
        dest: /var/tmp/postgresql.conf
      
    - name: Update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: "{{conf_dir}}/nginx.conf"
      notify:
        - restart web services

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: "restart web services"

