- hosts: staging
  become: yes

  vars:
    root_dir: /usr/share/nginx/html
    conf_dir: /etc/nginx
    nginx_port: 80

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
      
    - name: Copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      
    - name: Update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: "{{conf_dir}}/nginx.conf"
      notify:
        - restart web services

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: "restart web services"

