- hosts: staging
  become: yes

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
      
    - name: Update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart web services

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: "restart web services"

